___
<h1> Machine Learning </h1>
<h2> M. Sc. in Electrical and Computer Engineering </h2>
<h3> Instituto Superior de Engenharia / Universidade do Algarve </h3>

[MEEC](https://ise.ualg.pt/en/curso/1477) / [ISE](https://ise.ualg.pt) / [UAlg](https://www.ualg.pt)

Pedro J. S. Cardoso (pcardoso@ualg.pt)
___

To start, let us import some libraries

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer, MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold, StratifiedShuffleSplit

from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier

from sklearn import tree

# Decision Trees
## Classification

In this example we'll use the iris dataset. Following the same flow, it is now easy to train a Decision Tree Model

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [3]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    train_size=.75,
                                                    random_state=42)

Create the classifier and train it with the default parameters

In [4]:
dtc = DecisionTreeClassifier(random_state=42).fit(X_train, y_train)

And we get perfect score on training

In [5]:
score = dtc.score(X_train, y_train)
score

1.0

and also in test...!

In [6]:
score = dtc.score(X_test, y_test)
score

1.0

Ater this we can plot the tree

In [7]:
fig, axes = plt.subplots(figsize = (30, 30))

_ = tree.plot_tree(dtc,
                   feature_names = iris.feature_names,
                   class_names=iris.target_names,
                   filled = True)

Use the tree to predict some of the test examples...

In [8]:
print(iris.feature_names, '\n', X_test[:5], '\n', iris.target_names[:5])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
 [[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]
 ['setosa' 'versicolor' 'virginica']

If we do some cross validation using a stratified shuffle split that is not so perfect!

(https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) 
(https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedShuffleSplit.html) 

In the first example, then minimum number of samples required to be at a leaf node is 1.

In [9]:
skf = StratifiedShuffleSplit(n_splits=10,
                             random_state=1)

clf = DecisionTreeClassifier(random_state=1)

scores = cross_val_score(clf,
                         iris.data, iris.target, 
                         cv=skf)

print(f'scores:{scores}\nmu:{scores.mean()}')

scores:[0.93333333 0.93333333 0.8        0.93333333 0.93333333 0.86666667
 1.         0.86666667 0.93333333 0.93333333]
mu:0.9133333333333334

In the following example, we increase minimum number of samples required to be at a leaf node to be 3, giving a slight increase in performance

In [10]:
clf = DecisionTreeClassifier(random_state=1,
                             min_samples_leaf = 3)

scores = cross_val_score(clf,
                         iris.data, iris.target, 
                         cv=skf)

print(f'scores:{scores}\nmu:{scores.mean()}')

scores:[0.93333333 0.93333333 1.         0.93333333 0.93333333 0.93333333
 1.         0.86666667 0.93333333 0.93333333]
mu:0.9400000000000001

## Regression
https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html

Let us consider the Seoul Bike Sharing Demand dataset. The dataset contains the hourly count of rental bikes between years 2017 and 2018 in Seoul, Korea with the corresponding weather and seasonal information. The dataset can be downloaded from https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand but we have already downloaded it and saved it in the data folder.

Let us start by loading the dataset into a pandas dataframe.

In [11]:
import pandas as pd
df = pd.read_csv('./data/SeoulBikeData.csv')
df.head()

,Date,Rented Bike Count,Hour,Temperature(C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

By calling the dataframe's info method, we can see that there are no missing values but there are some categorical columns.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      8760 non-null   object
 1   Rented Bike Count         8760 non-null   int64
 2   Hour                      8760 non-null   int64
 3   Temperature(C)            8760 non-null   float64
 4   Humidity(%)               8760 non-null   int64
 5   Wind speed (m/s)          8760 non-null   float64
 6   Visibility (10m)          8760 non-null   int64
 7   Dew point temperature(C)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)   8760 non-null   float64
 9   Rainfall(mm)              8760 non-null   float64
 10  Snowfall (cm)             8760 non-null   float64
 11  Seasons                   8760 non-null   object
 12  Holiday                   8760 non-null   object
 13  Functioning Day           8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.3+ KB

The categorical columns need to be converted into, for example, dummy variables. 

A dummy variable is a numerical variable used in regression analysis to represent subgroups of the sample in your study. In research design, a dummy variable is often used to distinguish different treatment groups. for example the season column has four categories: Spring, Summer, Autumn, and Winter. We can convert this column into four columns, one for each category, and use 0 or 1 to indicate if the sample belongs to that category or not. To achieve this, we can use the pandas get_dummies method.

In [13]:
df = pd.get_dummies(df, columns=['Seasons', 'Holiday', 'Functioning Day'], drop_first=True)
df

,Date,Rented Bike Count,Hour,Temperature(C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons_Spring,Seasons_Summer,Seasons_Winter,Holiday_No Holiday,Functioning Day_Yes
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,False,False,True,True,True
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,False,False,True,True,True
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,False,False,True,True,True
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,False,False,True,True,True
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,False,False,False,True,True
8756,30/11/2018,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,False,False,False,True,True
8757,30/11/2018,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,False,False,False,True,True
8758,30/11/2018,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,False,False,False,True,True
8759,30/11/2018,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,False,False,False,True,True

We can split this column into two columns: month and day, and day of week. To achieve this, we can use the pandas to_datetime method as follows:

In [14]:
# make sure the date column is in datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

# create new columns for month, day, and day of week
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df['day_of_week'] = df['Date'].dt.day_of_week

# drop the original date column
df.drop('Date', axis=1, inplace=True)

Let us now recheck the dataframe's info method.

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rented Bike Count         8760 non-null   int64
 1   Hour                      8760 non-null   int64
 2   Temperature(C)            8760 non-null   float64
 3   Humidity(%)               8760 non-null   int64
 4   Wind speed (m/s)          8760 non-null   float64
 5   Visibility (10m)          8760 non-null   int64
 6   Dew point temperature(C)  8760 non-null   float64
 7   Solar Radiation (MJ/m2)   8760 non-null   float64
 8   Rainfall(mm)              8760 non-null   float64
 9   Snowfall (cm)             8760 non-null   float64
 10  Seasons_Spring            8760 non-null   bool
 11  Seasons_Summer            8760 non-null   bool
 12  Seasons_Winter            8760 non-null   bool
 13  Holiday_No Holiday        8760 non-null   bool
 14  Functioning Day_Yes       8760 non-null   bool
 15  month                     8760 non-null   int32
 16  day                       8760 non-null   int32
 17  day_of_week               8760 non-null   int32
dtypes: bool(5), float64(6), int32(3), int64(4)
memory usage: 829.9 KB

Since the target variable is the Rented Bike Count, we can split the dataframe into two dataframes: one with the target variable and another with the remaining variables.

In [16]:
X_seoul_bike = df.drop('Rented Bike Count', axis=1)
y_seoul_bike = df['Rented Bike Count']

The next step is to split the data into training and test sets.

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_seoul_bike, y_seoul_bike,
                                                    shuffle=True,
                                                    random_state=42,
                                                    test_size=0.1)

Now, we can train a decision tree regressor model.

In [18]:
dtr = DecisionTreeRegressor(random_state=0).fit(X_train, y_train)

Finaly, we score it

In [19]:
score = dtr.score(X_test, y_test)
score

0.876074032908466

And plot the predictions vs the true values

In [20]:
y_pred = dtr.predict(X_test)

plt.plot(y_test, y_pred, c='g', marker='.', linestyle='')
plt.plot(y_test, y_test, c='b')

plt.legend(["pred vs test", "perfect"])

plt.xlabel('test')
plt.ylabel('pred')

Text(0, 0.5, 'pred')

And plot the tree, which is quite big!

In [21]:
fig, axes = plt.subplots(figsize = (200, 80))

_ = tree.plot_tree(dtr,
               feature_names=df.columns,
               filled=True,
               fontsize=12)

The tree figure is too big to be seen in the notebook. We can save it to a file and open it in an image viewer.

In [22]:
fig.savefig("tree.png", dpi=fig.dpi)

To be more sure, let us do a cross validation experiment

In [23]:
# define the cross validation method
kfold = KFold(n_splits=5, 
              shuffle=True, 
              random_state=1)

# define the model
reg = DecisionTreeRegressor(random_state=1,
                            min_samples_leaf = 3)

# perform cross validation
scores = cross_val_score(reg,
                         X_seoul_bike, y_seoul_bike, 
                         cv=kfold)

print(f'scores:{scores}\nmu:{scores.mean()}')

scores:[0.86107542 0.84632268 0.86826205 0.88410959 0.8886347 ]
mu:0.8696808894603171

# Random Forest
## Classification

Let us perform the same experiment using a Random Forest Classifier. As always, we start by importing the necessary libraries, loading the dataset, and splitting it into training and test sets.

In [24]:
from sklearn.ensemble import RandomForestClassifier

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target, 
                                                    train_size=.75,
                                                    random_state=42)

Now, we can train a random forest classifier model.

In [25]:
rfc = RandomForestClassifier(n_estimators=100, # number of trees in the forest
                             n_jobs=-1, # use all available cores
                             min_samples_leaf = 1, # minimum number of samples required to be at a leaf node
                             ).fit(X_train, y_train)

And we get perfect score on training

In [26]:
scores = rfc.score(X_train, y_train)
print(f'scores:{scores}\nmu:{scores.mean()}')

AttributeError: 'float' object has no attribute 'mean'

and also in test...!

In [ ]:
scores = rfc.score(X_test, y_test)
print(f'scores:{scores}\nmu:{scores.mean()}')

To be more sure, let us do a cross validation experiment

In [ ]:
# define the cross validation method as a stratified shuffle split
sss = StratifiedShuffleSplit(n_splits=5, 
                             random_state=42
                             )

# define the model
rfc = RandomForestClassifier(n_estimators=100, # number of trees in the forest
                             n_jobs=-1, # use all available cores
                             min_samples_leaf = 3, # minimum number of samples required to be at a leaf node
                             )

# perform cross validation
scores = cross_val_score(rfc,  
                         iris.data, 
                         iris.target, 
                         cv=sss
                         )

print(f'scores:{scores}\nmu:{scores.mean()}')

## Regression

Let us perform the same experiment using a Random Forest Regressor. As always, we start by importing the necessary libraries, loading the dataset, and splitting it into training and test sets.

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_seoul_bike,
                                                    y_seoul_bike,
                                                    shuffle=True,
                                                    random_state=1,
                                                    test_size=0.1)

Now, we can train a random forest regressor model.

In [ ]:
rfr = RandomForestRegressor( n_estimators=100,
                             n_jobs=-1,
                             random_state=0).fit(X_train, y_train)

And we get the score which better than the decision tree

In [ ]:
y_pred = rfr.predict(X_test)

score = rfr.score(X_test, y_test)
score

In [ ]:
y_pred = rfr.predict(X_test)

plt.plot(y_test, y_pred, c='g', marker='.', linestyle='')
plt.plot(y_test, y_test, c='b')

plt.legend(["pred vs test", "perfect"])

plt.xlabel('test')
plt.ylabel('pred')

To be more sure, let us do a cross validation experiment

In [ ]:
# define the cross validation method
kfold = KFold(n_splits=5, 
              shuffle=True, 
              random_state=42)

# perform cross validation
scores = cross_val_score(rfr,  X_seoul_bike, y_seoul_bike, cv=kfold)
scores

In [ ]:
scores.mean()

## Grid Search cross validation

To find the best parameters for a model, we can use the GridSearchCV class. This class implements a "fit" and a "score" method

In [ ]:
from sklearn.model_selection import GridSearchCV

# define the cross validation method
kfold = KFold(n_splits=3, 
              shuffle=True, 
              random_state=42)

# define the model
rfc = RandomForestRegressor(n_jobs=-1)

# define the parameters to be tested
param_grid = {
    'n_estimators': [10, 100], # number of trees in the forest
    'min_samples_leaf': [1, 3, 5, 7, 9], # minimum number of samples required to be at a leaf node
    'max_depth': [None, 5, 10], # maximum depth of the tree
    'max_features': ['auto', 'sqrt', 'log2'], # number of features to consider when looking for the best split 
    'bootstrap': [True, False], # method of selecting samples for training each tree
    'random_state': [42], # seed used by the random number generator
    'n_jobs': [-1], # number of jobs to run in parallel
    'verbose': [3], # controls the verbosity when fitting and predicting
}

# define the grid search
grid_search = GridSearchCV(estimator=rfc, 
                           param_grid=param_grid, 
                           cv=kfold, 
                           n_jobs=-1, 
                           verbose=0)

# perform the grid search
grid_search.fit(X_seoul_bike, y_seoul_bike)

The best parameters are

In [ ]:
grid_search.best_params_

And the best score is

In [ ]:
grid_search.best_score_